import type { Metadata } from "next";
import "./globals.css";
import { Fira_Sans } from 'next/font/google'
const fira_Sans = Fira_Sans({
  weight: ["600","500","400"],
  subsets: ['latin'],
  variable: '--font-fira'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fira_Sans.variable}`}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
